language: php

php:
  - 5.6

env:
  global:
    - HOST=www.ocr-correction.local
    - BROWSER=firefox

addons:
  firefox: "41.0.1"
  hosts:
    - www.ocr-correction.local

services:
  - couchdb

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential apache2 libapache2-mod-fastcgi

install:
  # Directory permissions
  - sh -e .travis/scripts/permissions.sh

  # Copy config file
  - sudo cp config/config.test.php.sample config/config.test.php
  - sudo cp config/config.php.sample config/config.php

before_script:
  # PHP configuration
  - phpenv config-rm xdebug.ini
  - phpenv config-add .travis/travis.php.ini

  # PHP-FPM configuration
  - sh -e .travis/scripts/php-fpm.sh

  # Apache config
  - sh -e .travis/scripts/apache2-configure.sh

  # Apache vhosts
  - sh -e .travis/scripts/apache2-vhost.sh "$HOST"

  # Restart PHP-FCGI and Apache
  - phpenv rehash
  - sudo service apache2 restart

  # Install Composer dependencies
  - composer self-update
  - composer global require hirak/prestissimo
  - composer install
  
  # CouchDB views
  - php bin/initalize.php --create

  # Selenium
  - sh -e .travis/scripts/selenium.sh
  - sleep 5

script:
  - travis_retry php vendor/bin/phpunit -c Tests/$BROWSER.phpunit.xml --stderr
