language: php

php:
  - 5.5

env:
  global:
    - HOST=www.ocr-correction.local
    - BROWSER=firefox

services:
  - couchdb

install:
  # Install dependencies
  - sh -e .travis/scripts/apt-get.sh

  # Install Composer dependencies
  - composer self-update
  - composer global require hirak/prestissimo
  - composer install

before_script:
  # enable php-fpm because Travis doesn't do libapache2-mod-php5
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sh -e .travis/scripts/apache2-configure.sh
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # Apache web server config for vhosts
  - sh -e .travis/scripts/apache2-vhost.sh "$HOST"

  # PHP config
  - phpenv config-add .travis/travis.php.ini

  # Restart Apache
  - sudo service apache2 restart
  
  # CouchDB configuration
  - sudo service couchdb restart
  - sleep 3
  - curl -X PUT localhost:5984/ocr
  - curl -X PUT localhost:5984/ocr/_design/page -H "Content-Type:application/json" -d@.travis/couchdb/page.json
  - curl -X PUT localhost:5984/ocr/_design/textDiff -H "Content-Type:application/json" -d@.travis/couchdb/textDiff.json

  # Selenium
  - sh -e .travis/scripts/selenium.sh
  - sleep 3

script:
  - travis_retry php vendor/bin/phpunit -c Tests/$BROWSER.phpunit.xml --stderr
