language: php

php:
  - 5.6

env:
  global:
    - HOST=www.ocr-correction.local
    - BROWSER=firefox

addons:
  firefox: "41.0.1"
  hosts:
    - www.ocr-correction.local
  apt:
    packages:
      - apache2
      - build-essential
      - libapache2-mod-fastcgi
      - php5-cli
      - php5-common
      - php5-dev
      - php5-fpm
      - php5-curl
      - php-pear
      - locales
      - gettext
      - autoconf
      - xvfb
      - curl
      - cmake

services:
  - couchdb

install:
  # Install Composer dependencies
  - composer self-update
  - composer global require hirak/prestissimo
  - composer install

  # PHP configuration
  - phpenv config-add .travis/travis.php.ini
  - phpenv rehash

  # PHP-FPM configuration
  - sh -e .travis/scripts/php-fpm.sh

before_script:
  # Copy config file
  - sudo cp config/config.test.php.sample config/config.test.php
  - sudo cp config/config.php.sample config/config.php
  
  # Apache config
  - sh -e .travis/scripts/apache2-configure.sh

  # Apache vhosts
  - sh -e .travis/scripts/apache2-vhost.sh "$HOST"

  # Restart PHP-FCGI and Apache
  - phpenv rehash
  - sudo service apache2 restart
  
  # CouchDB views
  - curl -X PUT localhost:5984/ocr
  - curl -X PUT localhost:5984/ocr/_design/page -H "Content-Type:application/json" -d@.travis/couchdb/page.json
  - curl -X PUT localhost:5984/ocr/_design/textDiff -H "Content-Type:application/json" -d@.travis/couchdb/textDiff.json

  # Selenium
  - sh -e .travis/scripts/selenium.sh
  - sleep 3

script:
  - travis_retry php vendor/bin/phpunit -c Tests/$BROWSER.phpunit.xml --stderr
